[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "langchain-community>=0.4.1",
    "langchain-mistralai>=1.1.4",
    "langchain-pinecone>=0.2.13",
    "pypdf>=6.11.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.0",
    "rich>=15.0.0",
]
