[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "langchain>=1.4.2",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.4.0",
    "langchain-mistralai>=1.1.6",
    "langchain-pinecone>=0.2.13",
    "langgraph>=1.2.12",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "pypdf>=6.11.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.0",
    "rich>=15.0.0",
]
